---
# Default variables for wisepulse_pipeline role

# Directory where WisePulse repository is located
wisepulse_repo_path: /opt/WisePulse

# User that will run the pipeline
wisepulse_user: wisepulse

# Group for the wisepulse user
wisepulse_group: wisepulse

# Log directory for pipeline output
wisepulse_log_dir: /var/log/wisepulse

# When to run the pipeline (systemd timer format)
wisepulse_timer_oncalendar: "*-*-* 02:00:00"  # Daily at 2 AM

# LAPIS API configuration
wisepulse_api_base_url: https://api.db.wasap.genspectrum.org

# Fetch configuration (passed to Make)
wisepulse_fetch_days: 90              # Days of historical data to fetch
wisepulse_fetch_max_reads: 15000000   # 100 million reads (testing)
                                       # For production: 125000000 (125 million)

# LAPIS port for docker compose (optional, for when starting the API)
wisepulse_lapis_port: 8083

# NOTE: This role assumes the following are already installed:
# - Docker and Docker Compose
# - git
# Rust/Cargo will be automatically installed for the wisepulse user by this role.
