---
# Reusable task to log phase execution
# Variables:
#   - phase_number: Phase number (1-7)
#   - phase_name: Phase description
#   - phase_status: "start" or "complete" or "failed"
#   - phase_details: (optional) Additional details to log

- name: "Log {{ phase_name }} - {{ phase_status }}"
  shell: |
    echo "[$(date -Iseconds)] PHASE {{ phase_number }}: {{ phase_name }} - {{ phase_status | upper }}" >> /var/log/srsilo/update-pipeline.log
    {% if phase_details is defined %}
    echo "  Details: {{ phase_details }}" >> /var/log/srsilo/update-pipeline.log
    {% endif %}
  become: yes
  become_user: "{{ srsilo_user }}"
  changed_when: false
  delegate_to: localhost
