---
- name: Apply Kubernetes values to loculus cluster
  hosts: kubernetes
  tasks:
    - name: Ensure temp directory exists
      file:
        path: /tmp/loculus-values
        state: directory
        mode: '0750'

    - name: Copy decrypted values file
      copy:
        src: secrets/my-values.yaml
        dest: /tmp/loculus-values/my-values.yaml
        decrypt: yes

    - name: Apply Helm chart with values to loculus cluster
      shell: |
        kubectl config use-context k3d-loculusCluster 
        helm upgrade --install my-loculus /opt/loculus/loculus/kubernetes/loculus -f /tmp/loculus-values/my-values.yaml
      
    - name: Clean up decrypted values file
      file:
        path: /tmp/loculus-values/my-values.yaml
        state: absent   
