---
# Handlers for wisepulse_pipeline role

- name: reload systemd
  systemd:
    daemon_reload: yes
  become: yes

- name: restart docker
  systemd:
    name: docker
    state: restarted
  become: yes
