name: CI

on:
  push:

env:
  DOCKER_DEPENDENCY_IMAGE_NAME: ghcr.io/genspectrum/lapis-silo-dependencies
  DOCKER_IMAGE_NAME: ghcr.io/genspectrum/lapis-silo

jobs:
  endToEnd:
    name: Build docker images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4


      - shell: bash
        name: Start the docker compose
        run: |
          cargo build --release
          cp test_data/* silo_input
          make
          LAPIS_PORT=80 docker compose up
          curl localhost:80/sample/info
          docker compose down
