name: CI

on:
  push:

env:
  DOCKER_DEPENDENCY_IMAGE_NAME: ghcr.io/genspectrum/lapis-silo-dependencies
  DOCKER_IMAGE_NAME: ghcr.io/genspectrum/lapis-silo

jobs:
  endToEnd:
    name: End to end setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - shell: bash
        name: Process the data and run a docker container
        run: |
          cargo build --release
          cp test_data/* silo_input
          make all
          mkdir logs
          LAPIS_PORT=80 docker compose up --detach --wait
          curl localhost:80/sample/info
          docker compose down
